// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnlvqstrgpmiyrivmzha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBubHZxc3RyZ3BtaXlyaXZtemhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTEwNTUsImV4cCI6MjA3NDQyNzA1NX0.QRz2PnaWvanFogWJy4WfWPPZ8mVT8icW4Ph4jDOXpEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});